/*
===============================================================================
 Script Name : 05_magnitude_analysis.sql

 Description :
     Perform Magnitude Analysis across major business dimensions.

     This analysis measures the volume and magnitude of customers, products,
     sales, revenue, and quantities across countries, genders, categories,
     product lines, and customers.

     The objective is to understand how business activity is distributed
     across different dimensions before performing ranking analysis.
===============================================================================
*/


-- ==========================================================
-- 1. CUSTOMER MAGNITUDE ANALYSIS
-- ==========================================================

-- Find the total number of customers by country
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;


------------------------------------------------------------

-- Find the total number of customers by gender
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;


------------------------------------------------------------

-- Find the total number of customers by marital status
SELECT
    marital_status,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY marital_status
ORDER BY total_customers DESC;


-- ==========================================================
-- 2. PRODUCT MAGNITUDE ANALYSIS
-- ==========================================================

-- Find the total number of products by category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;


------------------------------------------------------------

-- Find the total number of products by subcategory
SELECT
    category,
    sub_category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY
    category,
    sub_category
ORDER BY total_products DESC;


------------------------------------------------------------

-- Find the average product cost in each category
SELECT
    category,
    AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC;


------------------------------------------------------------

-- Find the average product cost by product line
SELECT
    product_line,
    AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY product_line
ORDER BY average_cost DESC;


------------------------------------------------------------

-- Find the total number of products by product line
SELECT
    product_line,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY product_line
ORDER BY total_products DESC;


-- ==========================================================
-- 3. SALES MAGNITUDE BY PRODUCT
-- ==========================================================

-- Find total revenue generated by each product category
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


------------------------------------------------------------

-- Find total quantity sold by each product category
SELECT
    p.category,
    SUM(f.quantity) AS total_quantity_sold
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_quantity_sold DESC;


------------------------------------------------------------

-- Find total revenue generated by each product line
SELECT
    p.product_line,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
    ON p.product_key = f.product_key
GROUP BY p.product_line
ORDER BY total_revenue DESC;


------------------------------------------------------------

-- Find total quantity sold by each product line
SELECT
    p.product_line,
    SUM(f.quantity) AS total_quantity_sold
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
    ON p.product_key = f.product_key
GROUP BY p.product_line
ORDER BY total_quantity_sold DESC;


-- ==========================================================
-- 4. CUSTOMER SALES MAGNITUDE
-- ==========================================================

-- Find the total revenue generated by each customer
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
    ON c.customer_key = f.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;


------------------------------------------------------------

-- Find the total quantity purchased by each customer
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.quantity) AS total_quantity
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
    ON c.customer_key = f.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_quantity DESC;


------------------------------------------------------------

-- Find the total number of orders placed by each customer
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    COUNT(DISTINCT f.order_name) AS total_orders
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
    ON c.customer_key = f.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_orders DESC;


-- ==========================================================
-- 5. GEOGRAPHIC SALES MAGNITUDE
-- ==========================================================

-- Find total revenue generated by each country
SELECT
    c.country,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_revenue DESC;


------------------------------------------------------------

-- Find the distribution of items sold across countries
SELECT
    c.country,
    SUM(f.quantity) AS total_quantity_sold
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_quantity_sold DESC;


------------------------------------------------------------

-- Find the number of orders generated by each country
SELECT
    c.country,
    COUNT(DISTINCT f.order_name) AS total_orders
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_orders DESC;


-- ==========================================================
-- 6. CUSTOMER DEMOGRAPHIC SALES MAGNITUDE
-- ==========================================================

-- Find total revenue by customer gender
SELECT
    c.gender,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
    ON c.customer_key = f.customer_key
GROUP BY c.gender
ORDER BY total_revenue DESC;


------------------------------------------------------------

-- Find total quantity sold by customer gender
SELECT
    c.gender,
    SUM(f.quantity) AS total_quantity_sold
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
    ON c.customer_key = f.customer_key
GROUP BY c.gender
ORDER BY total_quantity_sold DESC;


------------------------------------------------------------

-- Find total revenue by marital status
SELECT
    c.marital_status,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
    ON c.customer_key = f.customer_key
GROUP BY c.marital_status
ORDER BY total_revenue DESC;


-- ==========================================================
-- 7. PRODUCT COST MAGNITUDE
-- ==========================================================

-- Compare the number of products and average cost by category
SELECT
    category,
    COUNT(product_key) AS total_products,
    AVG(cost) AS average_cost,
    MIN(cost) AS minimum_cost,
    MAX(cost) AS maximum_cost
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;


-- ==========================================================
-- 8. COMBINED CATEGORY PERFORMANCE
-- ==========================================================

-- Compare product volume, quantity sold, and revenue by category
SELECT
    p.category,
    COUNT(DISTINCT p.product_key) AS total_products,
    SUM(f.quantity) AS total_quantity_sold,
    SUM(f.sales_amount) AS total_revenue,
    AVG(f.price) AS average_selling_price
FROM gold.dim_products AS p
LEFT JOIN gold.fact_sales AS f
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;
