/*
===============================================================================
 Script Name : 07_business_questions.sql

 Description :
     Answer real-world business questions using the Gold Layer of the
     Data Warehouse.

     This script applies SQL aggregation, joins, filtering, date analysis,
     conditional logic, and window functions to translate raw business data
     into actionable insights.

     The analysis focuses on sales performance, customer behavior, product
     performance, geographic trends, and business concentration.

     This script represents the final analytical stage of the SQL
     Exploratory Data Analysis project.
===============================================================================
*/


-- ==========================================================
-- BUSINESS AREA 1: SALES PERFORMANCE
-- ==========================================================


-- Q1. What is the total revenue generated by the business?

SELECT
    SUM(sales_amount) AS total_revenue
FROM gold.fact_sales;


------------------------------------------------------------

-- Q2. What is the total number of orders and items sold?

SELECT
    COUNT(DISTINCT order_name) AS total_orders,
    SUM(quantity) AS total_items_sold
FROM gold.fact_sales;


------------------------------------------------------------

-- Q3. What is the average revenue generated per order?

SELECT
    SUM(sales_amount) * 1.0
    / NULLIF(COUNT(DISTINCT order_name), 0) AS average_order_value
FROM gold.fact_sales;


------------------------------------------------------------

-- Q4. How does revenue change from year to year?

SELECT
    YEAR(order_date) AS order_year,
    SUM(sales_amount) AS total_revenue,
    COUNT(DISTINCT order_name) AS total_orders
FROM gold.fact_sales
GROUP BY YEAR(order_date)
ORDER BY order_year;


------------------------------------------------------------

-- Q5. Which year generated the highest revenue?

SELECT TOP 1
    YEAR(order_date) AS order_year,
    SUM(sales_amount) AS total_revenue
FROM gold.fact_sales
GROUP BY YEAR(order_date)
ORDER BY total_revenue DESC;


-- ==========================================================
-- BUSINESS AREA 2: CUSTOMER ANALYSIS
-- ==========================================================


-- Q6. How many customers have actually placed an order?

SELECT
    COUNT(DISTINCT customer_key) AS active_customers
FROM gold.fact_sales;


------------------------------------------------------------

-- Q7. What percentage of customers have placed at least one order?

SELECT
    COUNT(DISTINCT fs.customer_key) * 100.0
    / NULLIF(COUNT(DISTINCT dc.customer_key), 0)
        AS customer_conversion_rate
FROM gold.dim_customers AS dc
LEFT JOIN gold.fact_sales AS fs
    ON dc.customer_key = fs.customer_key;


------------------------------------------------------------

-- Q8. Who are the top 10 highest-value customers?

SELECT TOP 10
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
    ON f.customer_key = c.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;


------------------------------------------------------------

-- Q9. Which customers have placed the most orders?

SELECT TOP 10
    c.customer_key,
    c.first_name,
    c.last_name,
    COUNT(DISTINCT f.order_name) AS total_orders
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
    ON f.customer_key = c.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_orders DESC;


------------------------------------------------------------

-- Q10. Which customers generate high revenue but place relatively
-- few orders?

SELECT TOP 10
    c.customer_key,
    c.first_name,
    c.last_name,
    COUNT(DISTINCT f.order_name) AS total_orders,
    SUM(f.sales_amount) AS total_revenue,
    SUM(f.sales_amount) * 1.0
        / NULLIF(COUNT(DISTINCT f.order_name), 0)
        AS average_order_value
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
    ON f.customer_key = c.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
HAVING COUNT(DISTINCT f.order_name) > 0
ORDER BY average_order_value DESC;


-- ==========================================================
-- BUSINESS AREA 3: PRODUCT ANALYSIS
-- ==========================================================


-- Q11. Which products generate the highest revenue?

SELECT TOP 10
    p.product_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
    ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC;


------------------------------------------------------------

-- Q12. Which products have the highest sales volume?

SELECT TOP 10
    p.product_name,
    SUM(f.quantity) AS total_quantity_sold
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
    ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_quantity_sold DESC;


------------------------------------------------------------

-- Q13. Which products generate the lowest revenue?

SELECT TOP 10
    p.product_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
    ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC;


------------------------------------------------------------

-- Q14. Which categories generate the most revenue?

SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
    ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


------------------------------------------------------------

-- Q15. Which category sells the highest number of items?

SELECT TOP 1
    p.category,
    SUM(f.quantity) AS total_quantity_sold
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
    ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY total_quantity_sold DESC;


------------------------------------------------------------

-- Q16. Which categories have many products but relatively low revenue?

SELECT
    p.category,
    COUNT(DISTINCT p.product_key) AS total_products,
    SUM(f.sales_amount) AS total_revenue,
    SUM(f.sales_amount) * 1.0
        / NULLIF(COUNT(DISTINCT p.product_key), 0)
        AS revenue_per_product
FROM gold.dim_products AS p
LEFT JOIN gold.fact_sales AS f
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY revenue_per_product ASC;


-- ==========================================================
-- BUSINESS AREA 4: GEOGRAPHIC ANALYSIS
-- ==========================================================


-- Q17. Which countries generate the most revenue?

SELECT
    c.country,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
    ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_revenue DESC;


------------------------------------------------------------

-- Q18. Which countries have the highest number of customers?

SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;


------------------------------------------------------------

-- Q19. Which countries have the highest number of orders?

SELECT
    c.country,
    COUNT(DISTINCT f.order_name) AS total_orders
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
    ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_orders DESC;


------------------------------------------------------------

-- Q20. Which countries generate the highest revenue per customer?

SELECT
    c.country,
    COUNT(DISTINCT c.customer_key) AS total_customers,
    SUM(f.sales_amount) AS total_revenue,
    SUM(f.sales_amount) * 1.0
        / NULLIF(COUNT(DISTINCT c.customer_key), 0)
        AS revenue_per_customer
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
    ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY revenue_per_customer DESC;


-- ==========================================================
-- BUSINESS AREA 5: CUSTOMER DEMOGRAPHICS
-- ==========================================================


-- Q21. Which gender contributes the most revenue?

SELECT
    c.gender,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
    ON f.customer_key = c.customer_key
GROUP BY c.gender
ORDER BY total_revenue DESC;


------------------------------------------------------------

-- Q22. Which marital-status group contributes the most revenue?

SELECT
    c.marital_status,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
    ON f.customer_key = c.customer_key
GROUP BY c.marital_status
ORDER BY total_revenue DESC;


-- ==========================================================
-- BUSINESS AREA 6: PRODUCT & CUSTOMER RELATIONSHIP
-- ==========================================================


-- Q23. Which product category is most popular among customers?

SELECT TOP 10
    p.category,
    COUNT(DISTINCT f.customer_key) AS unique_customers,
    SUM(f.quantity) AS total_quantity_sold,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
    ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY unique_customers DESC;


------------------------------------------------------------

-- Q24. Which products are purchased by the largest number of customers?

SELECT TOP 10
    p.product_name,
    COUNT(DISTINCT f.customer_key) AS unique_customers,
    SUM(f.quantity) AS total_quantity_sold
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
    ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY unique_customers DESC;


-- ==========================================================
-- BUSINESS AREA 7: BUSINESS CONCENTRATION
-- ==========================================================


-- Q25. What percentage of total revenue comes from the top 10 customers?

WITH customer_revenue AS
(
    SELECT
        customer_key,
        SUM(sales_amount) AS total_revenue
    FROM gold.fact_sales
    GROUP BY customer_key
),
ranked_customers AS
(
    SELECT
        customer_key,
        total_revenue,
        ROW_NUMBER() OVER (
            ORDER BY total_revenue DESC
        ) AS customer_rank
    FROM customer_revenue
)
SELECT
    SUM(total_revenue) AS top_10_customer_revenue,
    (
        SELECT SUM(sales_amount)
        FROM gold.fact_sales
    ) AS total_business_revenue,
    SUM(total_revenue) * 100.0 /
        NULLIF(
            (
                SELECT SUM(sales_amount)
                FROM gold.fact_sales
            ), 0
        ) AS top_10_revenue_percentage
FROM ranked_customers
WHERE customer_rank <= 10;


------------------------------------------------------------

-- Q26. What percentage of total revenue comes from the top 10 products?

WITH product_revenue AS
(
    SELECT
        product_key,
        SUM(sales_amount) AS total_revenue
    FROM gold.fact_sales
    GROUP BY product_key
),
ranked_products AS
(
    SELECT
        product_key,
        total_revenue,
        ROW_NUMBER() OVER (
            ORDER BY total_revenue DESC
        ) AS product_rank
    FROM product_revenue
)
SELECT
    SUM(total_revenue) AS top_10_product_revenue,
    (
        SELECT SUM(sales_amount)
        FROM gold.fact_sales
    ) AS total_business_revenue,
    SUM(total_revenue) * 100.0 /
        NULLIF(
            (
                SELECT SUM(sales_amount)
                FROM gold.fact_sales
            ), 0
        ) AS top_10_revenue_percentage
FROM ranked_products
WHERE product_rank <= 10;


-- ==========================================================
-- BUSINESS AREA 8: ORDER VALUE ANALYSIS
-- ==========================================================


-- Q27. What is the average order value by year?

SELECT
    YEAR(order_date) AS order_year,
    SUM(sales_amount) AS total_revenue,
    COUNT(DISTINCT order_name) AS total_orders,
    SUM(sales_amount) * 1.0
        / NULLIF(COUNT(DISTINCT order_name), 0)
        AS average_order_value
FROM gold.fact_sales
GROUP BY YEAR(order_date)
ORDER BY order_year;


------------------------------------------------------------

-- Q28. Which customers have an average order value above
-- the overall average order value?

WITH customer_orders AS
(
    SELECT
        customer_key,
        COUNT(DISTINCT order_name) AS total_orders,
        SUM(sales_amount) AS total_revenue
    FROM gold.fact_sales
    GROUP BY customer_key
)
SELECT
    customer_key,
    total_orders,
    total_revenue,
    total_revenue * 1.0
        / NULLIF(total_orders, 0) AS average_order_value
FROM customer_orders
WHERE
    total_revenue * 1.0 / NULLIF(total_orders, 0)
    >
    (
        SELECT
            SUM(sales_amount) * 1.0
            / NULLIF(COUNT(DISTINCT order_name), 0)
        FROM gold.fact_sales
    )
ORDER BY average_order_value DESC;


-- ==========================================================
-- BUSINESS AREA 9: TOP PRODUCT WITHIN EACH CATEGORY
-- ==========================================================


-- Q29. What is the highest-revenue product within each category?

WITH product_revenue AS
(
    SELECT
        p.category,
        p.product_name,
        SUM(f.sales_amount) AS total_revenue
    FROM gold.fact_sales AS f
    LEFT JOIN gold.dim_products AS p
        ON f.product_key = p.product_key
    GROUP BY
        p.category,
        p.product_name
),
ranked_products AS
(
    SELECT
        category,
        product_name,
        total_revenue,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY total_revenue DESC
        ) AS product_rank
    FROM product_revenue
)
SELECT
    category,
    product_name,
    total_revenue
FROM ranked_products
WHERE product_rank = 1
ORDER BY category;


-- ==========================================================
-- BUSINESS AREA 10: FINAL EXECUTIVE SUMMARY
-- ==========================================================


-- Q30. Generate a high-level business KPI summary.

SELECT
    SUM(sales_amount) AS total_revenue,
    COUNT(DISTINCT order_name) AS total_orders,
    SUM(quantity) AS total_items_sold,
    COUNT(DISTINCT customer_key) AS active_customers,
    COUNT(DISTINCT product_key) AS products_sold,
    AVG(price) AS average_selling_price,
    SUM(sales_amount) * 1.0
        / NULLIF(COUNT(DISTINCT order_name), 0)
        AS average_order_value,
    SUM(sales_amount) * 1.0
        / NULLIF(COUNT(DISTINCT customer_key), 0)
        AS revenue_per_customer
FROM gold.fact_sales;
