/*
===============================================================================
    10_performance_analysis.sql
===============================================================================

    Project:
    SQL Exploratory Data Analysis Project

    Purpose:
    Analyze yearly product performance by comparing each product's sales
    with its average sales performance and previous year's sales.

    Analysis Includes:
        1. Yearly product sales
        2. Average yearly sales
        3. Difference from average sales
        4. Performance vs average
        5. Previous year's sales
        6. Year-over-Year sales difference
        7. Year-over-Year performance classification

    Source Tables:
        gold.fact_sales
        gold.dim_products

===============================================================================
*/


-- ============================================================================
-- 1. YEARLY PRODUCT SALES
-- ============================================================================
-- Calculate total sales generated by each product for every year.

WITH yearly_product_sales AS
(
    SELECT
        YEAR(f.order_date) AS order_year,
        p.product_name,
        SUM(f.sales_amount) AS current_sales
    FROM gold.fact_sales AS f
    LEFT JOIN gold.dim_products AS p
        ON f.product_key = p.product_key
    WHERE f.order_date IS NOT NULL
    GROUP BY
        YEAR(f.order_date),
        p.product_name
)

SELECT
    order_year,
    product_name,
    current_sales
FROM yearly_product_sales
ORDER BY
    product_name,
    order_year;


-- ============================================================================
-- 2. COMPARE SALES WITH PRODUCT AVERAGE
-- ============================================================================
-- Compare each product's yearly sales against its average yearly sales.

WITH yearly_product_sales AS
(
    SELECT
        YEAR(f.order_date) AS order_year,
        p.product_name,
        SUM(f.sales_amount) AS current_sales
    FROM gold.fact_sales AS f
    LEFT JOIN gold.dim_products AS p
        ON f.product_key = p.product_key
    WHERE f.order_date IS NOT NULL
    GROUP BY
        YEAR(f.order_date),
        p.product_name
)

SELECT
    order_year,
    product_name,
    current_sales,

    AVG(current_sales) OVER (
        PARTITION BY product_name
    ) AS avg_sales,

    current_sales -
    AVG(current_sales) OVER (
        PARTITION BY product_name
    ) AS diff_avg,

    CASE
        WHEN current_sales >
             AVG(current_sales) OVER (
                 PARTITION BY product_name
             )
            THEN 'Above Avg'

        WHEN current_sales <
             AVG(current_sales) OVER (
                 PARTITION BY product_name
             )
            THEN 'Below Avg'

        ELSE 'Avg'
    END AS avg_change

FROM yearly_product_sales
ORDER BY
    product_name,
    order_year;


-- ============================================================================
-- 3. YEAR-OVER-YEAR PRODUCT PERFORMANCE
-- ============================================================================
-- Compare current year's product sales with the previous year's sales.

WITH yearly_product_sales AS
(
    SELECT
        YEAR(f.order_date) AS order_year,
        p.product_name,
        SUM(f.sales_amount) AS current_sales
    FROM gold.fact_sales AS f
    LEFT JOIN gold.dim_products AS p
        ON f.product_key = p.product_key
    WHERE f.order_date IS NOT NULL
    GROUP BY
        YEAR(f.order_date),
        p.product_name
)

SELECT
    order_year,
    product_name,
    current_sales,

    LAG(current_sales) OVER (
        PARTITION BY product_name
        ORDER BY order_year
    ) AS previous_year_sales,

    current_sales -
    LAG(current_sales) OVER (
        PARTITION BY product_name
        ORDER BY order_year
    ) AS diff_previous_year,

    CASE
        WHEN LAG(current_sales) OVER (
                 PARTITION BY product_name
                 ORDER BY order_year
             ) IS NULL
            THEN 'New Product'

        WHEN current_sales >
             LAG(current_sales) OVER (
                 PARTITION BY product_name
                 ORDER BY order_year
             )
            THEN 'Increase'

        WHEN current_sales <
             LAG(current_sales) OVER (
                 PARTITION BY product_name
                 ORDER BY order_year
             )
            THEN 'Decrease'

        ELSE 'No Change'
    END AS previous_year_change

FROM yearly_product_sales
ORDER BY
    product_name,
    order_year;


-- ============================================================================
-- 4. FINAL PRODUCT PERFORMANCE ANALYSIS
-- ============================================================================
-- Combine average performance and previous-year performance
-- into one analytical report.

WITH yearly_product_sales AS
(
    SELECT
        YEAR(f.order_date) AS order_year,
        p.product_name,
        SUM(f.sales_amount) AS current_sales
    FROM gold.fact_sales AS f
    LEFT JOIN gold.dim_products AS p
        ON f.product_key = p.product_key
    WHERE f.order_date IS NOT NULL
    GROUP BY
        YEAR(f.order_date),
        p.product_name
)

SELECT
    order_year,
    product_name,
    current_sales,

    -- Average yearly sales
    ROUND(
        AVG(current_sales) OVER (
            PARTITION BY product_name
        ),
        2
    ) AS avg_sales,

    -- Difference from average
    ROUND(
        current_sales -
        AVG(current_sales) OVER (
            PARTITION BY product_name
        ),
        2
    ) AS diff_avg,

    -- Performance compared with average
    CASE
        WHEN current_sales >
             AVG(current_sales) OVER (
                 PARTITION BY product_name
             )
            THEN 'Above Avg'

        WHEN current_sales <
             AVG(current_sales) OVER (
                 PARTITION BY product_name
             )
            THEN 'Below Avg'

        ELSE 'Avg'
    END AS avg_change,

    -- Previous year's sales
    LAG(current_sales) OVER (
        PARTITION BY product_name
        ORDER BY order_year
    ) AS py_sales,

    -- Difference from previous year
    current_sales -
    LAG(current_sales) OVER (
        PARTITION BY product_name
        ORDER BY order_year
    ) AS diff_py,

    -- Year-over-Year performance
    CASE
        WHEN LAG(current_sales) OVER (
                 PARTITION BY product_name
                 ORDER BY order_year
             ) IS NULL
            THEN 'New Product'

        WHEN current_sales >
             LAG(current_sales) OVER (
                 PARTITION BY product_name
                 ORDER BY order_year
             )
            THEN 'Increase'

        WHEN current_sales <
             LAG(current_sales) OVER (
                 PARTITION BY product_name
                 ORDER BY order_year
             )
            THEN 'Decrease'

        ELSE 'No Change'
    END AS py_change

FROM yearly_product_sales
ORDER BY
    product_name,
    order_year;
