/*
===============================================================================
    12_data_segmentation.sql
===============================================================================

    Project:
    SQL Exploratory Data Analysis Project

    Purpose:
    Segment customers and products into meaningful business groups based on
    purchasing behavior, revenue contribution, and product performance.

    Customer Segmentation:
        1. Customer revenue
        2. Order frequency
        3. Customer activity
        4. High / Medium / Low value customers

    Product Segmentation:
        1. Product revenue
        2. Product price range
        3. High / Medium / Low performing products

    Business Use:
    Helps identify high-value customers, understand customer purchasing
    behavior, and classify products based on their business performance.

===============================================================================
*/


-- ============================================================================
-- 1. CUSTOMER REVENUE SEGMENTATION
-- ============================================================================
-- Classify customers based on the total revenue they generate.

WITH customer_spending AS
(
    SELECT
        c.customer_key,
        CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
        SUM(f.sales_amount) AS total_spending
    FROM gold.fact_sales AS f
    LEFT JOIN gold.dim_customers AS c
        ON f.customer_key = c.customer_key
    GROUP BY
        c.customer_key,
        c.first_name,
        c.last_name
)

SELECT
    customer_key,
    customer_name,
    total_spending,

    CASE
        WHEN total_spending >= 5000 THEN 'High Value'
        WHEN total_spending >= 2000 THEN 'Medium Value'
        ELSE 'Low Value'
    END AS customer_segment

FROM customer_spending
ORDER BY
    total_spending DESC;


-- ============================================================================
-- 2. CUSTOMER SEGMENT SUMMARY
-- ============================================================================
-- Count customers and measure revenue generated by each customer segment.

WITH customer_spending AS
(
    SELECT
        c.customer_key,
        SUM(f.sales_amount) AS total_spending
    FROM gold.fact_sales AS f
    LEFT JOIN gold.dim_customers AS c
        ON f.customer_key = c.customer_key
    GROUP BY
        c.customer_key
),

customer_segments AS
(
    SELECT
        customer_key,
        total_spending,

        CASE
            WHEN total_spending >= 5000 THEN 'High Value'
            WHEN total_spending >= 2000 THEN 'Medium Value'
            ELSE 'Low Value'
        END AS customer_segment

    FROM customer_spending
)

SELECT
    customer_segment,
    COUNT(customer_key) AS total_customers,
    SUM(total_spending) AS total_revenue,
    AVG(total_spending) AS average_customer_spending
FROM customer_segments
GROUP BY
    customer_segment
ORDER BY
    total_revenue DESC;


-- ============================================================================
-- 3. CUSTOMER PURCHASE FREQUENCY SEGMENTATION
-- ============================================================================
-- Segment customers based on the number of orders they have placed.

WITH customer_orders AS
(
    SELECT
        customer_key,
        COUNT(DISTINCT order_name) AS total_orders
    FROM gold.fact_sales
    GROUP BY
        customer_key
)

SELECT
    customer_key,
    total_orders,

    CASE
        WHEN total_orders >= 10 THEN 'Frequent Customer'
        WHEN total_orders >= 5 THEN 'Regular Customer'
        ELSE 'Occasional Customer'
    END AS purchase_frequency_segment

FROM customer_orders
ORDER BY
    total_orders DESC;


-- ============================================================================
-- 4. CUSTOMER ACTIVITY SEGMENTATION
-- ============================================================================
-- Classify customers based on their total quantity purchased.

WITH customer_activity AS
(
    SELECT
        c.customer_key,
        CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
        SUM(f.quantity) AS total_quantity
    FROM gold.fact_sales AS f
    LEFT JOIN gold.dim_customers AS c
        ON f.customer_key = c.customer_key
    GROUP BY
        c.customer_key,
        c.first_name,
        c.last_name
)

SELECT
    customer_key,
    customer_name,
    total_quantity,

    CASE
        WHEN total_quantity >= 20 THEN 'Highly Active'
        WHEN total_quantity >= 10 THEN 'Moderately Active'
        ELSE 'Low Activity'
    END AS activity_segment

FROM customer_activity
ORDER BY
    total_quantity DESC;


-- ============================================================================
-- 5. PRODUCT REVENUE SEGMENTATION
-- ============================================================================
-- Classify products based on the revenue they generate.

WITH product_sales AS
(
    SELECT
        p.product_key,
        p.product_name,
        SUM(f.sales_amount) AS total_revenue
    FROM gold.fact_sales AS f
    LEFT JOIN gold.dim_products AS p
        ON f.product_key = p.product_key
    GROUP BY
        p.product_key,
        p.product_name
)

SELECT
    product_key,
    product_name,
    total_revenue,

    CASE
        WHEN total_revenue >= 10000 THEN 'High Performer'
        WHEN total_revenue >= 5000 THEN 'Medium Performer'
        ELSE 'Low Performer'
    END AS product_segment

FROM product_sales
ORDER BY
    total_revenue DESC;


-- ============================================================================
-- 6. PRODUCT PRICE SEGMENTATION
-- ============================================================================
-- Group products according to their selling price.

SELECT
    product_key,
    product_name,
    cost,

    CASE
        WHEN cost >= 500 THEN 'High Price'
        WHEN cost >= 200 THEN 'Medium Price'
        ELSE 'Low Price'
    END AS price_segment

FROM gold.dim_products
ORDER BY
    cost DESC;


-- ============================================================================
-- 7. PRODUCT SEGMENT SUMMARY
-- ============================================================================
-- Summarize the number of products and revenue generated by each
-- performance segment.

WITH product_sales AS
(
    SELECT
        p.product_key,
        p.product_name,
        SUM(f.sales_amount) AS total_revenue
    FROM gold.fact_sales AS f
    LEFT JOIN gold.dim_products AS p
        ON f.product_key = p.product_key
    GROUP BY
        p.product_key,
        p.product_name
),

product_segments AS
(
    SELECT
        product_key,
        product_name,
        total_revenue,

        CASE
            WHEN total_revenue >= 10000 THEN 'High Performer'
            WHEN total_revenue >= 5000 THEN 'Medium Performer'
            ELSE 'Low Performer'
        END AS product_segment

    FROM product_sales
)

SELECT
    product_segment,
    COUNT(product_key) AS total_products,
    SUM(total_revenue) AS total_revenue,
    AVG(total_revenue) AS average_revenue
FROM product_segments
GROUP BY
    product_segment
ORDER BY
    total_revenue DESC;


-- ============================================================================
-- 8. CUSTOMER RFM-STYLE SEGMENTATION
-- ============================================================================
-- Create a simplified customer segmentation using:
-- Recency  : Days since the customer's last purchase
-- Frequency: Number of orders
-- Monetary : Total revenue generated
--
-- This is a simplified RFM-style analysis for exploratory purposes.

WITH customer_metrics AS
(
    SELECT
        c.customer_key,
        CONCAT(c.first_name, ' ', c.last_name) AS customer_name,

        MAX(f.order_date) AS last_order_date,

        COUNT(DISTINCT f.order_name) AS total_orders,

        SUM(f.sales_amount) AS total_spending

    FROM gold.fact_sales AS f
    LEFT JOIN gold.dim_customers AS c
        ON f.customer_key = c.customer_key

    GROUP BY
        c.customer_key,
        c.first_name,
        c.last_name
)

SELECT
    customer_key,
    customer_name,
    last_order_date,

    DATEDIFF(
        DAY,
        last_order_date,
        (SELECT MAX(order_date) FROM gold.fact_sales)
    ) AS recency_days,

    total_orders,
    total_spending,

    CASE
        WHEN total_spending >= 5000
             AND total_orders >= 10
             AND DATEDIFF(
                    DAY,
                    last_order_date,
                    (SELECT MAX(order_date) FROM gold.fact_sales)
                 ) <= 365
            THEN 'High Value Active'

        WHEN total_spending >= 2000
             AND total_orders >= 5
            THEN 'Medium Value'

        ELSE 'Low Value / Inactive'
    END AS customer_segment

FROM customer_metrics

ORDER BY
    total_spending DESC;


/*
===============================================================================
    END OF DATA SEGMENTATION ANALYSIS
===============================================================================
*/
